/*
 * Copyright 2014-2024 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license.
 */

package com.example.customplugin

import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.provider.Property
import org.jetbrains.dokka.gradle.dsl.DokkaGradlePluginDsl
import org.jetbrains.dokka.gradle.dsl.plugins.DokkaPluginConfiguration
import org.jetbrains.dokka.gradle.dsl.plugins.DokkaPluginsContainer

// TODO: make it working somehow?
public abstract class DokkaHtmlMermaidGradlePlugin : Plugin<Project> {
    override fun apply(target: Project) {
        TODO("Not yet implemented")
    }
}

@DokkaGradlePluginDsl
public interface DokkaHtmlMermaidPluginConfiguration : DokkaPluginConfiguration {
    public val lightTheme: Property<String>
    public val darkTheme: Property<String>
    public val mermaidVersion: Property<String>
}

@DokkaGradlePluginDsl // TODO: is it needed or will be generated by gradle?
public fun DokkaPluginsContainer.htmlMermaid(configure: DokkaHtmlMermaidPluginConfiguration.() -> Unit) {

}
