site_name: Dokka

# Meta tags (placed in header)
site_description: Dokka is an API documentation engine for Kotlin, performing the same function as the Javadoc tool for Java
site_author: JetBrains
site_url: https://github.com/Kotlin/dokka

# Repository (add link to repository on each page)
repo_name: dokka
repo_url: https://github.com/Kotlin/dokka
edit_uri: edit/master/docs-developer/src/doc/docs/

# Copyright (shown at the footer)
copyright: 'Copyright &copy; 2023 JetBrains'

# Material theme
theme:
  name: 'material'
  favicon: favicon.svg
  social:
    - type: 'github'
      link: 'https://github.com/Kotlin/dokka'
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - navigation.top

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - def_list
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format

# Dev server binding for livereload
dev_addr: 127.0.0.1:3001

nav:
  - Home:
      - index.md
      - User guides: https://kotlinlang.org/docs/dokka-introduction.html
      - Developer guides: developer_guide/introduction.md
      - Community: developer_guide/community/slack.md
  - User guides:
      - https://kotlinlang.org/docs/dokka-introduction.html
  - Developer guides:
      - Developer guides: developer_guide/introduction.md
      - Workflow: developer_guide/workflow.md
      - Internals:
          - Architecture: developer_guide/architecture/architecture_overview.md
          - Data model:
              -  Documentables: developer_guide/architecture/data_model/documentable_model.md
              -  Page & Content: developer_guide/architecture/data_model/page_content.md
              -  Extra properties: developer_guide/architecture/data_model/extra.md
          - Extensions:
              - Extension points: developer_guide/architecture/extension_points/extension_points.md
              - Core extension points: developer_guide/architecture/extension_points/core_extension_points.md
              - Base extensions: developer_guide/architecture/extension_points/base_plugin.md
              - Generation implementations: developer_guide/architecture/extension_points/generation_implementations.md
      - Plugin development:
          - Plugin development: developer_guide/plugin-development/introduction.md
          - Sample plugin tutorial: developer_guide/plugin-development/sample-plugin-tutorial.md
  - Community:
      - Slack: developer_guide/community/slack.md

extra_css:
  - dokka_colors.css
