<#macro display>
    <div class="footer">
        <a href="#content" id="go-to-top-link" class="footer--button footer--button_go-to-top"></a>
        <span>${footerMessage}</span>
        <span class="pull-right">
        <span>Generated by </span>
        <a class="footer--link" href="https://github.com/Kotlin/dokka">
            <span>dokka</span>
            <span class="footer--external-link-icon"></span>
        </a>
    </span>
    </div>
</#macro>