<#macro display>
    <div class="footer">
        <a href="#content" id="go-to-top-link" class="navigation-controls--btn navigation-controls--btn_go-to-top"></a>
        <span>${footerMessage}</span>
        <span class="pull-right">
            <span>Generated by </span>
            <a class="footer--link footer--link_external" href="https://github.com/Kotlin/dokka">
                <span>dokka</span>
            </a>
        </span>
    </div>
</#macro>