/*
 * Copyright 2014-2025 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license.
 */

import React from 'react';

export interface PageModel {
    title: string;
    items: string[];
}

export const App = ({data}: { data: PageModel }) => {
    return (
        <div className="dokka-page">
            <h1>{data.title}</h1>
            <ul>
                {data.items.map((item, idx) => (
                    <li key={idx}>{item}</li>
                ))}
            </ul>
            <footer>Generated by GraalJS</footer>
        </div>
    );
};