name: API check

on: pull_request

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  apiCheck:
    name: binary compatibility
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          arguments: apiCheck --stacktrace
