name: API check

on: pull_request

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  apiCheck:
    name: binary compatibility
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-cleanup: always
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
      - run: ./gradlew apiCheck --stacktrace
