name: Gradle check

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'gradle/**'

jobs:
  wrapper:
    name: wrapper checksums
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
