name: Deploy developer docs to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'docs-developer/**'
  release:
    types: [ published ]

jobs:
  docs:
    if: github.repository == 'Kotlin/dokka'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: dokka
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-cleanup: always
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
      - name: Get current Dokka version
        run: echo "DOKKA_VERSION=`./gradlew :properties | grep '^version:.*' | cut -d ' ' -f 2`" >> $GITHUB_ENV
        working-directory: ./dokka
      - name: Build docs
        run: ./gradlew buildMkDocsSite -Pdokka_version=$DOKKA_VERSION --info
        working-directory: ./dokka
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dokka/docs-developer/build/mkdocs
          keep_files: true
          full_commit_message: Publish ${{ env.DOKKA_VERSION }} documentation
