name: Test [thorough]

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test-matrix:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        javaVersion: [ 8, 11, 17, 21 ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
      - name: Run tests under Windows
        if: matrix.os == 'windows-latest'
        # Running tests with the Gradle daemon on windows agents leads to some very strange
        # JVM crashes for some reason. Most likely a problem of Gradle/GitHub/Windows server
        run: >
          ./gradlew test --stacktrace --no-daemon --no-parallel --continue 
          "-Dorg.gradle.jvmargs=-Xmx1g -XX:MaxMetaspaceSize=500m"
          "-Porg.jetbrains.dokka.javaToolchain.testLauncher=${{ matrix.javaVersion }}"
      - name: Run tests under Ubuntu/Macos
        if: matrix.os != 'windows-latest'
        run: >
          ./gradlew test --stacktrace --continue
          "-Porg.jetbrains.dokka.javaToolchain.testLauncher=${{ matrix.javaVersion }}"
