name: Test [thorough]

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  matrix:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        javaVersion: [ 8, 11, 17 ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'
      - uses: gradle/gradle-build-action@v2
        env:
          ORG_GRADLE_PROJECT_org.jetbrains.dokka.javaToolchain.test: ${{ matrix.javaVersion }}
        with:
          gradle-home-cache-cleanup: true
          arguments: clean test --stacktrace
