name: Test [thorough]

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test-matrix:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        javaVersion: [ 8, 11, 17, 21 ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
      - name: Run tests
        run: >
          ./gradlew test --stacktrace --continue
          "-Porg.jetbrains.dokka.javaToolchain.testLauncher=${{ matrix.javaVersion }}"
