name: Test [thorough]

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test-matrix:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        javaVersion: [ 8, 11, 17, 21 ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set longpaths support for Windows
        if: matrix.os == 'windows-latest'
        # Avoid failing tests on Windows with "cannot create directory at X. Filename too long"
        # This command will fail if run on a Linux build agent with "could not lock config file: Permission denied"
        run: git config --system core.longpaths true
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
      - name: Run tests
        run: >
          ./gradlew check --stacktrace --continue
          "-Porg.jetbrains.dokka.integration_test.skip=true"
          "-Porg.jetbrains.dokka.javaToolchain.testLauncher=${{ matrix.javaVersion }}"
      - name: Upload build reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
           name: build-reports-${{ runner.os }}-${{ matrix.javaVersion }}-${{ github.action }}-${{ github.run_id }}
           path: |
              **/build/reports/
              **/*.hprof
              **/*.log
           if-no-files-found: ignore
